### ISSUE TITLE
implement account verification codes expiration

### ISSUE THREAD

**Issue by lucasmenendez** [vocdoni/saas-backend#15]
Currently, the verification codes generated to verify new accounts are valid forever. This behaviour is vulnerable to brute force attacks that attempt to verify an account by trying random codes. To prevent this type of attack, we need to create codes with an expiration date. 

If verification codes can expire, the API should provide some information, such as when the current verification code for an account will expire, or support for resending a verification code when the current one expires.

New API endpoints:
* `GET /users/verify/code?email={emailToVerifyCode}` 
  * **response**
  ```json
  {
    "valid": true,
    "expiration": "2009-11-10T23:00:00Z"
  }
  ```
  
* `POST /users/verify/code`
  * **body**
  ```json
  {
     "email": "{emailToResendCode}"
     // "phone": "+01000000000"
  }
  ```
  * **response**
    * `OK 200`: New code sent to the user.
    * `401 Unauthorized`: The current code associated with this user is still valid.

**Comment by selankon** [comment]
Rather than add a expiration time, to prevent this vulnerability, is better to add a max attempt count (1 or 2 for example), and if exceeded the code becomes invalid and a new email have to be requested.

On the other hand, I am agree to add expiration dates on the code, but also to add the possibility to request new code before expiration time, to prevent mail problems. 

But in this case the thing here is that a user can request new codes an arbitrary number of times and cause problems on the server or either the email providers mark us as spam, so taking in account with that, maybe is not the best idea. Or maybe we can add a minimum time to request new code or a captcha. 

The faster solution may be to add attempt count and expiration time, and don´t let the user to request new code until the expiration time.

**Comment by lucasmenendez** [comment]
So @selankon you suggest to include a count of validation attempts to also limit by this limit and not only by the expiration time?

**Comment by selankon** [comment]
Yes, exactly that. 

Because if you put for example 5 minutes, this are 5 minutes that you can try random codes. 

Anyway, if codes are strong enough and you put api rate limit, brute force attack shouldn't be easy

**Comment by lucasmenendez** [comment]
@selankon In any case, the first endpoint proposed is still needed because the UI needs to show to the user when a new code can be resent when the attempt limit is reached.
